# Generated by Django 5.1.1 on 2024-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='medias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.setor')),
                ('usuarios', models.ManyToManyField(to='tasks.usuario')),
            ],
        ),
    ]
